#!/usr/bin/env bash
# End-to-end local build for the Sublyne project.
#
# Pipeline (see .claude/skills/building-and-releasing/SKILL.md):
#   1. Build the Nuxt 3 frontend with the obfuscated-path placeholder
#      so the Go server can substitute the real /<webpath>/ at serve
#      time. The frontend `build` script also writes an SPA bootstrap
#      `index.html` from the Vite manifest (Nuxt's `ssr: false` output
#      otherwise just contains "Redirecting…" stubs and is not usable
#      as a static site).
#   2. Stage the frontend output into
#      control-plane/internal/webassets/frontend_dist/.
#   3. Build the Rust dataplane as a statically-linked
#      x86_64-unknown-linux-musl binary and stage it into
#      control-plane/internal/dataplaneasset/sublyne-dataplane so the
#      Go embed picks it up. Phase 8a introduces this step — earlier
#      phases just had a hello-world stub crate.
#   4. `go build -tags=embed` → sublyne-linux-amd64 at the repo root.
#      The output is always linux-amd64.
#
# Designed to run on Linux. Windows developers run this under WSL2 or
# inside a Linux container; the produced artifact is always linux-amd64.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

# Placeholder string the SPA bakes in via app.baseURL. The Go server
# replaces every occurrence with the runtime /<web_path>/ when serving
# HTML/JS/CSS. Must match
# control-plane/internal/webassets/spa.go::PlaceholderWebPath exactly.
NUXT_APP_BASE_URL="/__SUBLYNE_WEB_PATH__/"
export NUXT_APP_BASE_URL

# Allow the Rust target triple to be overridden (e.g. with -gnu for
# environments that don't have musl-tools installed). The release
# default is musl so the binary needs no glibc at runtime.
RUST_TARGET="${RUST_TARGET:-x86_64-unknown-linux-musl}"

# Compute the version *before* any build step runs. `git describe
# --dirty` walks the working tree; if a generator step later in this
# script ever modifies a tracked file (mode-bit change, autogenerated
# code, etc.), the version string would silently grow a "-dirty"
# suffix on tagged releases. Snapshotting up front keeps the released
# binary reporting its exact tag.
VERSION="$(git describe --tags --dirty --always 2>/dev/null || echo 'unknown')"
echo "==> Version: ${VERSION}"

echo "==> Building frontend (baseURL=${NUXT_APP_BASE_URL})"
(
  cd "$REPO_ROOT/frontend"
  # Use --no-frozen-lockfile until a pnpm-lock.yaml is committed. Once
  # the first build pipeline succeeds and the lockfile lands in source
  # control, we can tighten this to --frozen-lockfile for reproducibility.
  if [ -f pnpm-lock.yaml ]; then
    pnpm install --frozen-lockfile
  else
    pnpm install --no-frozen-lockfile
  fi
  pnpm build
)

echo "==> Staging frontend dist"
rm -rf "$REPO_ROOT/control-plane/internal/webassets/frontend_dist"
mkdir -p "$REPO_ROOT/control-plane/internal/webassets/frontend_dist"
cp -r "$REPO_ROOT/frontend/.output/public/." \
      "$REPO_ROOT/control-plane/internal/webassets/frontend_dist/"

# Drop the SSR server runtime — we only want the static dist embedded.
rm -rf "$REPO_ROOT/frontend/.output/server" 2>/dev/null || true

echo "==> Building Rust dataplane (release, target=${RUST_TARGET})"
(
  cd "$REPO_ROOT/data-plane"
  # Make sure the musl target is installed on the active toolchain.
  # `rustup target add` is idempotent — no-op when the target is
  # already present. This is safer than grepping the installed list,
  # which can return empty if rust-toolchain.toml points at a channel
  # that isn't fully provisioned yet (e.g. on a fresh CI runner).
  if command -v rustup >/dev/null 2>&1; then
    if ! rustup target add "${RUST_TARGET}" >/dev/null 2>&1; then
      echo "    ! Could not install Rust target ${RUST_TARGET}."
      echo "      Try: rustup target add ${RUST_TARGET}"
      echo "      Or:  pass RUST_TARGET=x86_64-unknown-linux-gnu to fall back to glibc."
      exit 1
    fi
  fi
  cargo build --release --target "${RUST_TARGET}"
)

echo "==> Staging dataplane binary"
DATAPLANE_BIN="$REPO_ROOT/data-plane/target/${RUST_TARGET}/release/sublyne-dataplane"
DATAPLANE_DST_DIR="$REPO_ROOT/control-plane/internal/dataplaneasset"
mkdir -p "${DATAPLANE_DST_DIR}"
cp "${DATAPLANE_BIN}" "${DATAPLANE_DST_DIR}/sublyne-dataplane"
chmod 0755 "${DATAPLANE_DST_DIR}/sublyne-dataplane"

echo "==> Building Go control plane (linux-amd64, embed tag, version=${VERSION})"
(
  cd "$REPO_ROOT/control-plane"
  GOOS=linux GOARCH=amd64 \
    go build \
      -tags=embed \
      -ldflags="-s -w -X main.version=${VERSION}" \
      -o "$REPO_ROOT/sublyne-linux-amd64" \
      ./cmd/sublyne
)

echo "==> Done."
ls -lh "$REPO_ROOT/sublyne-linux-amd64"
